### PR TITLE
KFSTI-2079

### PR DESCRIPTION
**Pull request by smith750**
Using refactoring to clarify the logic of when an Award may next be billed by a CINV doc

### CODE REVIEW

**Comment by kfsci** [comment]
Can one of the admins verify this patch?

**Comment by kkronenb** [comment]
verified

**Comment by kkronenb** [comment]
ok to test

**Comment by kkronenb** [comment]
looks like that comment worked, but jenkins is queued up on a diff pr.

**Comment by kkronenb** [comment]
test this please

**Comment by kfsci** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.kfs.kuali.org/job/Unit-Test-kfs-oracle/35/
Test PASSed.

**Pull request merged**
