### PR TITLE
KFSTI-1377

### PR DESCRIPTION
**Pull request by smith750**
Script to move files to standard Maven config destinations

### CODE REVIEW

**Comment by kkronenb** [comment]
Do we want to create a /bin dir to start collecting scripts?

**Comment by bhutchinson** [comment]
Yes, that sounds like a good idea to me.

**Comment by smith750** [comment]
Added bin path; the script still looks to work correctly, either run in the kfs home directory or from the bin directory

**Comment by kkronenb** [comment]
Looks good, thanks.

**Pull request merged**
