### PR TITLE
UAF-1625_UAF-1713

### PR DESCRIPTION
**Pull request by Perrinek**
UAF-1625 and UAF-1713 Vendor Name/Address fields, All Caps and Length Limits.

### CODE REVIEW

**Comment by kfsci** [comment]
Can one of the engineers verify this patch?

**Comment by kfsci** [comment]
Can one of the engineers verify this patch?

**Comment by smith750** [comment]
I'm going to guess this PR was not meant for foundation....

**Comment by Perrinek** [comment]
Sorry, bad pull request.

Julie

**Comment by Perrinek** [comment]
Sorry, bad pull request! Please delete.

**Comment by smith750** [comment]
Thanks Julie!

**Pull request closed without merging**
