### PR TITLE
UAF-1733 update pom file to bring in local changes to rice code

### PR DESCRIPTION
**Pull request by jshard**
Hi heather, I made updates to the kfs pom file similar to the change made for the kim-ldap code with this pull request. https://github.com/ua-eas/kfs/commit/ac732e75c7ea61a787998aeeb729bd29b9241847#diff-600376dffeb79835ede4a0b285078036
After we merge this, I'll run the UA custom build and deploy to dev and see if Scott's changes with UAF-1030 show up in the application. thanks.

### CODE REVIEW

**Comment by kfsci** [comment]
Can one of the engineers verify this patch?

**Comment by kfsci** [comment]
Can one of the engineers verify this patch?

**Comment by heather-lo** [comment]
This PR was made against the wrong repository. Go ahead and close. Sorry!

**Comment by smith750** [comment]
No problem - thanks!

**Pull request closed without merging**
