### PR TITLE
KFS ignore ide files

### PR DESCRIPTION
**Pull request by jcaddel**
Didn't see a specific jira for this.

### CODE REVIEW

**Comment by bhutchinson** [comment]
We did have a JIRA for that, at least the .classpath part: https://jira.kuali.org/browse/KFSMI-13177 however, we hadn't pulled it into our current sprint or backlog yet.

**Comment by jcaddel** [comment]
i'll redo this as KFSMI-13177 then?

**Comment by kkronenb** [comment]
Lets talk about this one Monday morning since there may be more we want to do such as removing both eclipse and intellij metadata.

**Comment by jcaddel** [comment]
Redoing this with a corresponding jira ticket

**Pull request closed without merging**
