### PR TITLE
UAR-2378: Updating rice version to ua-rel1-SNAPSHOT

### PR DESCRIPTION
**Pull request by nataliac06**

### CODE REVIEW

**Comment by kfsci** [comment]
Can one of the engineers verify this patch?

**Comment by kfsci** [comment]
Can one of the engineers verify this patch?

**Comment by nataliac06** [comment]
Sorry this patch is not valid, this was meant just for the University of Arizona's implementation in another branch.

**Comment by smith750** [comment]
no worries - that's what we'd figured

**Pull request closed without merging**
